server:
  port: 8082

spring:
  profiles:
    active: core-prd, db-prd, found-prd
  application:
    name: foundation-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

ribbon:
  eureka:
    enabled: true

#lcn分布式事务
#tx-lcn:
#  client:
#    manager-address: 192.168.1.21:8070
#  springcloud:
#    loadbalance:
#      enabled: true
